// Pädagogische Startwerte, keine diagnostisch validierten Grenzwerte.
export const CONFIG = Object.freeze({
  GENERAL_SESSION_MS: 6 * 60_000, FOCUS_SESSION_MS: 4 * 60_000,
  REMAINDER_SESSION_MS: 5 * 60_000,
  FAST_RESPONSE_MS: 6000, REMAINDER_FAST_RESPONSE_MS: 10000,
  INTERRUPTION_MS: 60000, RECENT_WINDOW: 12,
  MASTERY_MIN_ATTEMPTS: 6, MASTERY_ACCURACY: .9, MASTERY_FAST_STREAK: 3,
  SECURE_MIN_ATTEMPTS: 3, SECURE_ACCURACY: .8,
  LEVEL_2_MIN_OBSERVATIONS: 600, LEVEL_2_MIN_RECENT_OBSERVATIONS: 100,
  LEVEL_2_RECENT_WINDOW: 200, LEVEL_2_MIN_ACCURACY: .95,
  LEVEL_2_MIN_MASTERY_COVERAGE: .8, LEVEL_2_MIN_FAMILY_COVERAGE: .9,
  LEVEL_2_MAX_MEDIAN_MS: 6000,
  SPACING_TASKS: 4, FOCUS_FAMILIES: 8, FOCUS_SHARE: .72,
  EASY_SHARE: .15, COVERAGE_SHARE: .2, HISTORY_DAYS: 90,
  DEV_GENERAL_MS: 30000, DEV_FOCUS_MS: 20000
});
export const TEXT = Object.freeze({done:'Training für heute geschafft. Bis morgen!', correct:'✓ Richtig', wrong:'✕ Noch nicht', next:'Weiter', check:'Prüfen'});
export function durations(dev = false) {
  return {a:dev ? CONFIG.DEV_GENERAL_MS : CONFIG.GENERAL_SESSION_MS,
    b:dev ? CONFIG.DEV_FOCUS_MS : CONFIG.FOCUS_SESSION_MS,
    rest:dev ? CONFIG.DEV_FOCUS_MS : CONFIG.REMAINDER_SESSION_MS};
}
