import test from 'node:test';
import assert from 'node:assert/strict';
import {TASKS,REMAINDERS} from '../content.js';
import {observe,mastery,priority,selectTask,unlockProgress,median,focusFamilies} from '../learning-engine.js';
import {freshState,ensureDay,saveState,loadState} from '../storage.js';
import {recordAnswer,finishPhase} from '../session.js';
import {compare} from '../statistics.js';
import {CONFIG,durations} from '../config.js';
import {canShareFile,themeForDate} from '../share-card.js';
test('All 500 forms have exactly one answer; all 450 remainder tasks are valid',()=>{
 assert.equal(TASKS.length,500);assert.equal(new Set(TASKS.map(t=>t.id)).size,500);
 for(const t of TASKS){let candidates=[];for(let n=0;n<=100;n++){const a=t.a,b=t.b,p=a*b;const valid=({product:a*b===n,right:a*n===p,left:n*b===p,quotient:p/a===n,divisor:n!==0&&p/n===b})[t.form];if(valid)candidates.push(n);}assert.deepEqual(candidates,[t.answer]);assert(Number.isInteger(t.answer));}
 assert.equal(REMAINDERS.length,450);for(const t of REMAINDERS){const dividend=Number(t.label.split(' ')[0]);assert.equal(dividend,t.a*t.answer+t.remainder);assert(t.remainder>0&&t.remainder<t.a);}
});
test('Errors and slow retrieval get priority; repeated fast answers earn mastery',()=>{const t=TASKS[17],model={};const base=priority(t,model);for(let i=0;i<6;i++)observe(model,t,false,4000);assert(priority(t,model)>base);const slow={};for(let i=0;i<6;i++)observe(slow,t,true,15000);assert.equal(mastery(slow[t.id]),'slow');assert(priority(t,slow)>base);const fast={};for(let i=0;i<6;i++)observe(fast,t,true,2500);assert.equal(mastery(fast[t.id]),'automated');assert(priority(t,fast)<base);assert(priority(t,fast)>0);observe(fast,t,true,300000);assert.equal(median(fast[t.id].recent.filter(x=>x.ms!==null).map(x=>x.ms)),2500);});
test('Scheduler interleaves families, includes easy and mastered facts, covers all rows',()=>{let seed=42;const rng=()=>((seed=(seed*1664525+1013904223)>>>0)/2**32);const model={};for(const t of TASKS)for(let i=0;i<6;i++)observe(model,t,true,2000);let recent=[],easy=0;const seen=new Set();for(let i=0;i<1500;i++){const t=selectTask(model,{recent},rng);assert(!recent.slice(-CONFIG.SPACING_TASKS).some(x=>x.family===t.family));seen.add(t.a);easy+=Number(t.easy);recent.push(t);recent=recent.slice(-4);}assert.equal(seen.size,10);assert(easy>100);});
test('Level 2 requires broad mastery and stays unlocked',()=>{const s=freshState();s.level1Attempts=1000;s.recentLevel1=Array.from({length:200},()=>({ok:true,ms:2000}));for(let i=0;i<10;i++)observe(s.model,TASKS[0],true,2000);assert.equal(unlockProgress(s),false);for(const t of TASKS)for(let i=0;i<6;i++)observe(s.model,t,true,2000);assert.equal(unlockProgress(s),true);s.level2=true;s.model={};s.recentLevel1=[];assert.equal(unlockProgress(s),true);});
test('Reload, new day and permanent unlock survive serialization',()=>{const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};const s=freshState();ensureDay(s,'2026-09-18');s.day.stage='a';s.day.elapsed=42000;s.level2=true;saveState(s,storage);const read=loadState(storage).state;assert.equal(read.day.elapsed,42000);ensureDay(read,'2026-09-19');assert.equal(read.day.stage,'ready');assert.equal(read.history.length,1);assert(read.level2);assert(loadState({getItem:()=>'{bad'}).blocked);assert.equal(saveState(s,{setItem(){throw Error();}}),false);});
test('Two phases finish without a third round; defaults and dev timing are separate',()=>{const s=freshState();ensureDay(s);s.day.stage='a';recordAnswer(s,TASKS[0],false,8000);finishPhase(s);assert.equal(s.day.stage,'between');assert(s.day.focus.includes(TASKS[0].family));s.day.stage='b';recordAnswer(s,TASKS[0],true,2000);finishPhase(s);assert.equal(s.day.stage,'done');assert.equal(durations().a,360000);assert.equal(durations().b,240000);assert.equal(durations(true).a,30000);});
test('No fabricated comparisons, identical task forms only',()=>{const a=[{id:'a',family:'f',ok:true,ms:9000}],b=[{id:'b',family:'f',ok:true,ms:1000}];assert.equal(compare(a,b,['f']).adequate,false);assert.equal(compare(a,b,['f']).faster,0);});
test('Share detection covers unavailable, false, throwing and supported APIs; themes rotate',()=>{assert.equal(canShareFile({},{}),false);assert.equal(canShareFile({share(){},canShare:()=>false},{}),false);assert.equal(canShareFile({share(){},canShare(){throw Error();}},{}),false);assert.equal(canShareFile({share(){},canShare:()=>true},{}),true);assert.equal(new Set(['2026-09-18','2026-09-19','2026-09-20'].map(themeForDate)).size,3);});

test('Focus prioritizes erroneous families over slow correct families, with no-error fallback',()=>{const rows=[{id:TASKS[0].id,family:TASKS[0].family,ok:false,ms:3000},{id:TASKS[60].id,family:TASKS[60].family,ok:true,ms:15000}];assert.deepEqual(focusFamilies(rows,{}),[TASKS[0].family]);assert.deepEqual(focusFamilies(rows.slice(1),{}),[TASKS[60].family]);});
